- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - wget
        - unzip
        - epel-release
        - mysql
        - mariadb
        - mariadb-server
        
    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Enable Remi PHP 7.4 repository
      yum_repository:
        name: remi-php74
        description: Remi's PHP 7.4 RPM repository for Enterprise Linux 7
        baseurl: https://rpms.remirepo.net/enterprise/7/php74/x86_64/
        gpgcheck: yes
        gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
        enabled: yes

    - name: Install PHP and PHP MySQL module
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-mysql

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copy file with owner and permissions
      copy:
        src: /tmp/wordpress/.
        dest: /var/www/html
        owner: apache
        group: apache
        mode: '0755'
        remote_src: yes

    - name: Restart Apache
      service:
        name: httpd
        state: restarted

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
